runtime: php73

env_variables:
  APP_KEY: YOUR_APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  DB_DATABASE: YOUR_DB_DATABASE
  DB_USERNAME: YOUR_DB_USERNAME
  DB_PASSWORD: YOUR_DB_PASSWORD
  DB_SOCKET: "/cloudsql/shaped-crawler-312912:us-central1:kaidah"

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: .*
  script: auto