runtime: php73

env_variables:
  APP_NAME: Kaidah
  APP_ENV: production
  APP_KEY: YOUR_APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  DB_DATABASE: YOUR_DB_DATABASE
  DB_USERNAME: YOUR_DB_USERNAME
  DB_PASSWORD: YOUR_DB_PASSWORD
  DB_SOCKET: "/cloudsql/shaped-crawler-312912:us-central1:kaidah"
  MAIL_MAILER: smtp
  MAIL_HOST: YOUR_MAIL_HOST
  MAIL_PORT: 587
  MAIL_USERNAME: YOUR_MAIL_USERNAME
  MAIL_PASSWORD: YOUR_MAIL_PASSWORD
  MAIL_ENCRYPTION: tls
  MAIL_FROM_ADDRESS: YOUR_MAIL_FROM_ADDRESS
  MAIL_FROM_NAME: YOUR_MAIL_FROM_NAME

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
