steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: bash
  args: 
  - "-c"
  - |
  sed -i '' "s#YOUR_APP_KEY#$(php artisan key:generate --show --no-ansi)#" app.yaml
  sed -i '' "s#YOUR_DB_DATABASE#${_DB_DATABASE}#" app.yaml
  sed -i '' "s#YOUR_DB_USERNAME#${_DB_USERNAME}#" app.yaml
  sed -i '' "s#YOUR_DB_PASSWORD#${_DB_PASSWORD}#" app.yaml
  gcloud app deploy  app.yaml
timeout: "1600s"